[build]
  command = "npm run build-with-oss"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18" # 使用稳定的Node.js版本
  NPM_FLAGS = "--no-audit --no-fund"
  VITE_UNSAFE_EVAL = "true" # 允许svga.min.js使用eval
  # OSS配置环境变量（需要在Netlify后台设置）
  # OSS_ACCESS_KEY_ID = "your_access_key_id"
  # OSS_ACCESS_KEY_SECRET = "your_access_key_secret"
  # OSS_REGION = "oss-cn-chengdu"
  # OSS_BUCKET = "uiweb"

# 单页应用路由重写规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# 添加Content-Security-Policy头，允许eval执行和OSS图片加载
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; img-src 'self' data: blob: https://*.aliyuncs.com https://*.alicdn.com https://*.oss-cn-*.aliyuncs.com; style-src 'self' 'unsafe-inline';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 为静态资源添加缓存头
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"