/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BigbannerPad: typeof import('./components/square/bigbanner/bigbanner-pad.vue')['default']
    BigbannerPhone: typeof import('./components/square/bigbanner/bigbanner-phone.vue')['default']
    Button: typeof import('./components/arco/button.vue')['default']
    Ceshi: typeof import('./components/test/ceshi.vue')['default']
    Examples: typeof import('./components/general/upload/examples.vue')['default']
    Minibanner: typeof import('./components/square/minibanner/minibanner.vue')['default']
    Neirong: typeof import('./components/guangchang/neirong.vue')['default']
    PopUpPad: typeof import('./components/pop-up/pop-up-pad.vue')['default']
    PopUpPage: typeof import('./components/pop-up/pop-up-page.vue')['default']
    PopUpPhone: typeof import('./components/pop-up/pop-up-phone.vue')['default']
    ResourceList: typeof import('./components/pop-up/resource-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SquarePad: typeof import('./components/square/square-pad.vue')['default']
    SquarePhone: typeof import('./components/square/square-phone.vue')['default']
    Subjects: typeof import('./components/square/subjects/subjects.vue')['default']
    SubjectsPad: typeof import('./components/square/subjects/subjects-pad.vue')['default']
    Top: typeof import('./components/guangchang/top.vue')['default']
    TopPad: typeof import('./components/square/top/top-pad.vue')['default']
    Upload: typeof import('./components/test/upload.vue')['default']
    UploadPictureCard: typeof import('./components/general/upload/upload-picture-card.vue')['default']
    UploadSimple: typeof import('./components/general/upload/upload-simple.vue')['default']
    UploadSvga: typeof import('./components/general/upload/upload-svga.vue')['default']
  }
}
